workflows:
  ios-workflow:
    name: "iOS Release"
    
    environment:
      flutter: "3.40.0-0.2.pre"
    
    scripts:
      - name: "检查环境"
        script: |
          echo "Flutter 版本："
          flutter --version
          echo "Dart 版本："
          dart --version
      
      - name: "解决依赖"
        script: |
          rm -f pubspec.lock
          flutter pub get --no-offline
      
      - name: "iOS 构建"
        script: |
          flutter clean
          flutter build ios --release
      
      - name: "打包"
        script: |
          cd ios
          xcode-project build-ipa
    
    artifacts:
      - build/ios/ipa/*.ipa